### PR TITLE
removing const float*

### LINKED ISSUE #559: Strange `-Wcast-align` warning from `clang-3.9`
I saw the following strange warning (as an error) from `clang-3.9`.  ( Here's [actual GH-Actions log](https://github.com/t-mat/xxHash/runs/3345251571#step:7:23) )

```
clang-3.9 -Werror -Wall -Wextra -Wconversion -Wcast-qual -Wcast-align -Wshadow \
          -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement \
          -Wstrict-prototypes -Wundef -Wpointer-arith -Wformat-security -Wvla \
          -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls \
          -Wstrict-overflow=2 -Wno-sign-conversion -DXXHSUM_DISPATCH=1 -c -o xxhash.o xxhash.c

In file included from xxhash.c:43:
./xxhash.h:3868:56: error:
    cast from 'const xxh_u8 *' (aka 'const unsigned char *') to 'const float *'
    increases required alignment from 1 to 4 [-Werror,-Wcast-align]

    XXH_ALIGN(64)        const float* const src  = (float const*) XXH3_kSecret;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'd like to know there's good solution for this issue.

### PR DESCRIPTION
**Pull request by Cyan4973**
to fix #559

### CODE REVIEW

File: xxhash.h [hunk 1]
```diff
@@ -3865,8 +3865,8 @@ XXH_FORCE_INLINE XXH_TARGET_SSE2 void XXH3_initCustomSecret_sse2(void* XXH_RESTR
 #       endif
         int i;
 
-        XXH_ALIGN(64)        const float* const src  = (float const*) XXH3_kSecret;
-        XXH_ALIGN(XXH_SEC_ALIGN) __m128i*       dest = (__m128i*) customSecret;
+        const __m128i* const src16 = (const __m128i *)XXH3_kSecret;
```
Comment (Cyan4973) [inline xxhash.h]: As expected, this variant fails the `-Wcast-align` test on older `clang` version, 
as these compilers fail to notice that `XXH3_kSecret` is correctly aligned, 
since they only take into consideration the source type `const unsigned char*`, but not its alignment `XXH_ALIGN(64)`.

Note that `const float*` generates the same warning, it only differs in the amount of alignment required.

**Comment by Cyan4973** [comment]
This variant should now pass the `-Wcast-align` check of `clang`, including older versions.
Its code is also less obscure.
